version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalTest1Project
  gitServerName: SomaIBM
  gitUrl: https://github.com/Somasekhar-K-IBM
  gitUsername: Somasekhar-K-IBM
  gitBranch: main
services:
- serviceName: project.externaltest1.integrations:DafFlow
  packages:
  - name: ExternalTest1Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
